// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz3szzF4r2X1AbgnjbEsBlChKXFfK64ME',
    appId: '1:675495427417:web:a7b71f40d63d92a618e048',
    messagingSenderId: '675495427417',
    projectId: 'flutter-eccomer-app',
    authDomain: 'flutter-eccomer-app.firebaseapp.com',
    storageBucket: 'flutter-eccomer-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6enjD6E0a4x0kHmTnUYDX41T2tQ-MoZY',
    appId: '1:675495427417:android:55d490c35df3b3df18e048',
    messagingSenderId: '675495427417',
    projectId: 'flutter-eccomer-app',
    storageBucket: 'flutter-eccomer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLGB5FaA0lpav7CVGpc4XtPYO2AcLPgOg',
    appId: '1:675495427417:ios:544c3baa8967f52818e048',
    messagingSenderId: '675495427417',
    projectId: 'flutter-eccomer-app',
    storageBucket: 'flutter-eccomer-app.appspot.com',
    iosClientId: '675495427417-s949h4jvfb51ohshtemt902g9b80qah0.apps.googleusercontent.com',
    iosBundleId: 'com.example.galaxia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLGB5FaA0lpav7CVGpc4XtPYO2AcLPgOg',
    appId: '1:675495427417:ios:7fb521ef8f67e5a918e048',
    messagingSenderId: '675495427417',
    projectId: 'flutter-eccomer-app',
    storageBucket: 'flutter-eccomer-app.appspot.com',
    iosClientId: '675495427417-92dipoc0oj1nhfk2fv928pff5vu8ikfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.galaxia.RunnerTests',
  );
}
